### ISSUE TITLE
How to use in Mac OS 10.14 ?

### ISSUE THREAD

**Issue by vitali-ausianik** [acrogenesis/jsonview-safari#18]
Hello Guys,
Does it possible to use this extension in Mac OS 10.14? Looks like they removed possibility to install extension from other source except App Store. And also they still didn't implemented any way to search extension in App Store. Can you please provide direct link on App Store with this extension?

Thanks!

**Comment by Moorviper** [comment]
As mentioned in the readme:


Apple changed their Safari Extensions policy and now I need a Developer Account which costs $100 USD to release new bug fixes and features. Please send me some cash to gather the $100. Thanks! https://www.changetip.com/tipme/acrogenesis

**Comment by vitali-ausianik** [comment]
Thank you for explanation
