### ISSUE TITLE
Doesn't work on files around 1mb and larger

### ISSUE THREAD

**Issue by mattshepherd** [acrogenesis/jsonview-safari#2]
this seems to fail when dealing with anything other than a minimal amount of data.

**Comment by acrogenesis** [comment]
Hey @mattshepherd I've had this problem to it seems to be a matter on how jsonview parses the json data. You can try out another plugin I made which works better in this cases.

https://github.com/acrogenesis/JSONAce

**Comment by mattshepherd** [comment]
Thanks, that doesn't seem to work either. Here is an example if you are wanting to give it a try:

http://results.skitosea.com/api/v1/2014/results

**Comment by acrogenesis** [comment]
It does work on my mac, which version of OS X do you have and which version of Safari.

![screen shot 2015-04-08 at 11 15 04 am](https://cloud.githubusercontent.com/assets/1312687/7049627/9536ba66-dde0-11e4-9658-93722435cbd8.png)

**Comment by mattshepherd** [comment]
10.10.2 and 8.0.4

I have only tested on my main machine 2014 Core i7 11” Macbook Air with 8GB RAM.

**Comment by acrogenesis** [comment]
Could you update to 10.10.3 (comes with safari 8.0.5), and let me no if it still fails. (It was released today I was on the beta before)

**Comment by mattshepherd** [comment]
Still no go.

**Comment by acrogenesis** [comment]
@mattshepherd I found the error, the download link for version 1.2 was wrong so you had 1.1 (this was a known problem on 1.1). Restart your safari and in a moment it should update. I tried it on a 2013 MacBookPro and it worked great

**Comment by mattshepherd** [comment]
Working. Safari had already updated it. Just had to refresh.

Thanks.
