### ISSUE TITLE
Request for new feature

### ISSUE THREAD

**Issue by visualight** [acrogenesis/jsonview-safari#3]
It would be nice to have a button for switching to RAW mode or JSON mode the content of the page.
Thanks

**Comment by acrogenesis** [comment]
Great idea! How/Where would you like this button to be?

**Comment by visualight** [comment]
Like this picture.
The buttons appears when the mouse over the screen.

![1](https://cloud.githubusercontent.com/assets/3457651/7422247/9b9c511a-ef8b-11e4-8ebd-b295ef887dba.jpg)

**Comment by acrogenesis** [comment]
That looks awesome, do you want to go ahead an do the PR? Or can you wait till I get some time and do it. :+1:

**Comment by visualight** [comment]
I have no time for this moment : i work for a node project and i learn also laravel 5 framework.
So you have time to do this but it will be great for me to have this update soon as possible :-)

**Comment by acrogenesis** [comment]
@visualight It's done. Restart your safari for it to update. I'd also recommend this other plugin also built by me [JSONAce](https://github.com/acrogenesis/JSONAce/).
