### ISSUE TITLE
Not pretty printing JSON

### ISSUE THREAD

**Issue by conradwt** [acrogenesis/jsonview-safari#4]
The extension is no longer pretty printing the JSON.  For example, when I navigating to the following location, I seeing the JSON as the normal raw text:

```
http://www.raywenderlich.com/downloads/videos/books.json
```

**Comment by acrogenesis** [comment]
@conradwt I've just release v1.4.1 fixing this issue. I'd also recommend this other plugin also built by me [JSONAce](https://github.com/acrogenesis/JSONAce/)
