### ISSUE TITLE
packagist.org main page rendered as JSON instead of actual page.

### ISSUE THREAD

**Issue by alexzabolotny** [acrogenesis/jsonview-safari#5]
There is a JSON code on the page as a part of manual. Somehow that code is picked up as a main content of the page and replaces all other stuff.

Steps to reproduce:
1. Visit https://packagist.org/ and observe main page with content;
2. Install JSONView extension in Safari 8.0.5;
3. Visit https://packagist.org/;
4. Observe JSON instead of page content from step 1:

![screen shot 2015-05-12 at 14 03 24](https://cloud.githubusercontent.com/assets/49417/7586703/d450cf36-f8af-11e4-90b8-c11553310a62.png)

**Comment by acrogenesis** [comment]
@alexzabolotny I've fixed this, please restart Safari for the update to be applied. I'll close this now if you are still having trouble feel free to reopen it.
