### ISSUE TITLE
Error Installing Extension

### ISSUE THREAD

**Issue by WingedToaster** [acrogenesis/jsonview-safari#8]
I'm getting this error when trying to install the extension
![untitled-2](https://cloud.githubusercontent.com/assets/4502315/7813667/76b28490-0382-11e5-9e4c-3157a1740342.png)

**Comment by acrogenesis** [comment]
Thats strange, could you tell me a little bit more about your setup? eg. Which OSX version do you have? Safari version? Other plugins installed?

**Comment by WingedToaster** [comment]
Mac Pro, Safari Version 8.0.6 (10600.6.3)

**Comment by WingedToaster** [comment]
I do have JsonView 1.6 already installed and I'm trying to get the update to 1.7

**Comment by acrogenesis** [comment]
Check Automatic updates are on and restart safari, that should work
![screen shot 2015-05-26 at 9 42 27 pm](https://cloud.githubusercontent.com/assets/1312687/7827704/28cc6cb4-03f0-11e5-92cc-ba4bf25f9437.png)

**Comment by WingedToaster** [comment]
This is already set in my safari.

**Comment by acrogenesis** [comment]
Was this solved? I'm closing the issue now. Please re-open if you still have trouble

**Comment by WingedToaster** [comment]
Yes, this is installing now. Thanks.
